export type PricingSnapshotExplainRow = {
  channel_id: string;
  master_item_id: string;
  channel_product_id: string;
  external_variant_code: string | null;
  current_product_sync_profile?: string | null;
  master_base_price_krw: number;
  shop_margin_multiplier: number;
  material_raw_krw: number;
  material_final_krw: number;
  labor_raw_krw: number;
  labor_pre_margin_adj_krw: number;
  labor_post_margin_adj_krw: number;
  labor_sell_total_krw: number;
  labor_sell_master_krw: number;
  labor_sell_decor_krw: number;
  master_labor_base_sell_krw: number;
  master_labor_center_sell_krw: number;
  master_labor_sub1_sell_krw: number;
  master_labor_sub2_sell_krw: number;
  master_plating_sell_krw: number;
  master_labor_base_cost_krw: number;
  master_labor_center_cost_krw: number;
  master_labor_sub1_cost_krw: number;
  master_labor_sub2_cost_krw: number;
  master_plating_cost_krw: number;
  master_center_qty: number;
  master_sub1_qty: number;
  master_sub2_qty: number;
  master_labor_sell_profile_krw: number;
  master_labor_cost_profile_krw: number;
  absorb_item_count: number;
  absorb_total_krw: number;
  absorb_base_labor_krw: number;
  absorb_stone_labor_krw: number;
  absorb_plating_krw: number;
  absorb_etc_krw: number;
  absorb_general_class_krw: number;
  absorb_material_class_krw: number;
  total_pre_margin_adj_krw: number;
  total_post_margin_adj_krw: number;
  price_after_margin_krw: number;
  base_adjust_krw: number;
  delta_material_krw: number;
  delta_size_krw: number;
  delta_color_krw: number;
  delta_decor_krw: number;
  delta_other_krw: number;
  delta_total_krw: number;
  target_price_raw_krw: number;
  rounded_target_price_krw: number;
  override_price_krw: number | null;
  floor_price_krw: number;
  final_target_before_floor_krw: number;
  floor_clamped: boolean;
  final_target_price_krw: number;
  tick_gold_krw_g: number;
  tick_silver_krw_g: number;
  compute_request_id: string;
  computed_at: string;

  // V2 extension fields (optional during rollout)
  pricing_algo_version?: string;
  calc_version?: string | null;
  material_code_effective?: string | null;
  material_basis_resolved?: "GOLD" | "SILVER" | "NONE" | string | null;
  material_purity_rate_resolved?: number | null;
  material_adjust_factor_resolved?: number | null;
  effective_tick_krw_g?: number | null;
  net_weight_g?: number | null;
  current_channel_price_krw?: number | null;
  diff_krw?: number | null;
  diff_pct?: number | null;

  labor_cost_applied_krw?: number | null;
  labor_sell_total_plus_absorb_krw?: number | null;
  absorb_total_krw_raw?: number | null;
  absorb_total_krw_applied?: number | null;
  absorb_excluded_from_price_krw?: number | null;

  base_labor_sell_plus_absorb_krw?: number | null;
  stone_labor_sell_plus_absorb_krw?: number | null;
  plating_labor_sell_plus_absorb_krw?: number | null;
  etc_labor_sell_plus_absorb_krw?: number | null;
  decor_labor_sell_plus_absorb_krw?: number | null;

  fee_rate?: number | null;
  min_margin_rate_total?: number | null;
  cost_sum_krw?: number | null;
  material_pre_fee_krw?: number | null;
  labor_pre_fee_krw?: number | null;
  fixed_pre_fee_krw?: number | null;
  candidate_pre_fee_krw?: number | null;
  candidate_price_krw?: number | null;
  min_margin_price_krw?: number | null;
  guardrail_price_krw?: number | null;
  guardrail_reason_code?: string | null;
  final_target_price_v2_krw?: number | null;

  labor_component_json?: Record<string, {
    labor_cost_krw?: number;
    labor_absorb_applied_krw?: number;
    labor_absorb_raw_krw?: number;
    labor_cost_plus_absorb_krw?: number;
    labor_sell_krw?: number;
    labor_sell_plus_absorb_krw?: number;
    labor_class?: string;
  }> | null;
  absorb_total_applied_krw?: number | null;
  absorb_total_raw_krw?: number | null;
};

export type PricingSnapshotExplainResponse = {
  data: PricingSnapshotExplainRow;
};
